### ISSUE TITLE
FR: Support canvas

### ISSUE THREAD

**Issue by michaellw** [Phantom1003/obsidian-slide-note#1]
It doesn't seem to work with canvas, please support for displaying pdf pages and comments in canvas.

**Comment by Phantom1003** [comment]
Do you mean render text on the pages?
If yes, you can click the page and then you will get a drawboard, you can generate the required code from it.

**Comment by michaellw** [comment]
I mean the grammar is OK in the page, but if I use it in the obsidian canvas, it does not work, neither in card or imported note, the content is not shown.
![image](https://user-images.githubusercontent.com/276357/236682607-6e6637a6-ccc5-4500-97f9-892839e1cf95.png)
![image](https://user-images.githubusercontent.com/276357/236682620-ec5abb75-0576-4a01-9240-ac54ef91f31f.png)
![image](https://user-images.githubusercontent.com/276357/236682634-c6c781f9-fa06-4057-b1a0-d95467a663a1.png)

**Comment by Phantom1003** [comment]
got it, thanks for your advice

**Comment by michaellw** [comment]
As a block embed also does not work, also does not show the content.

**Comment by Phantom1003** [comment]
In order to avoid Slide Note from rendering the old content after switching the active file, I checked the currently open file and stopped rendering if it was different.
Referring to a code block in another file will incorrectly trigger this logic.
This bug should be fixed in version 0.0.5.

**Comment by michaellw** [comment]
It worked, great job!
