### ISSUE TITLE
FR: 操作逻辑优化

### ISSUE THREAD

**Issue by michaellw** [Phantom1003/obsidian-slide-note#2]
Hello，当前的操作逻辑使用上感觉有点奇怪：

- 当"link pages"选项激活时或者"link"参数设为true时，单击页面会直接打开链接文档，此时无法打开或激活选中页的pdf canvas进行标注
- 当"link pages"选项未激活时，每次点击页面都会打开右边栏的pdf canvas，此时无法打开链接的文档

能否将操作逻辑改为：

- 单击页面：啥也不发生
- 双击页面：打开链接的文档
- Alt/Ctrl/Shift + 单机页面：在右边pane打开或激活选中页的pdf canvas，而非在右边栏，因为右边栏通常比较窄，每次都因为标注而调整右边栏的宽度真的很烦人！

希望可以优化一下，谢谢！

**Comment by Phantom1003** [comment]
Yes, the current click event is a bit confusing, the link option is reserved for compatibility with better-pdf, and I actually plan to remove this feature subsequently.
Can you describe why you need this link option?

**Comment by Phantom1003** [comment]
In version 0.0.6, the link field has been removed.
The drawboard now requires a double click to open, and a new text field has been added to support selection of text on the page.

**Comment by michaellw** [comment]
I think the link option is still necessary, the page may be referenced in different places, or in the canvas, when I want to view the context of the current page, I need to open the original pdf to view the context.
