### ISSUE TITLE
[SlideNote] Invalid Parameters: attachments/***.pdf # file path: No such file or directory

### ISSUE THREAD

**Issue by aliamini87** [Phantom1003/obsidian-slide-note#3]
Hi
Thank you with this awesome plugin.
Unfortunately, I still can't use it. Because It can't find my pdf file. 

```slide-note
file: attachments/UCAM-CL-TR-696.pdf	# file path 
```
I wrote the path  in any format you can imagine. relative, absolute, with quotation, without quotation, with space in the file name, without that, etc. It didn't work in any of them.

windows 10
latest obsidian version

Thanks

**Comment by Phantom1003** [comment]
Is there any error message? What is the directory path of the note and the pdf?

**Comment by aliamini87** [comment]
Error message is in the title of the issue :

[[SlideNote] Invalid Parameters: attachments/***.pdf # file path: No such file or directory](https://github.com/Phantom1003/obsidian-slide-note/issues/3#top)

directory is attachments/UCAM-CL-TR-696.pdf

**Comment by Phantom1003** [comment]
Please remove the `# file path` part

**Comment by aliamini87** [comment]
I already remove that and the error changes:

[SlideNote] Invalid Parameters: paramsRaw.page.split is not a function

**Comment by Phantom1003** [comment]
It looks like you didn't specify the page option, no doubt this is a bug and I will fix it as soon as possible.
If you want to show all pages, for now, you can append `page: 0` to clear this error.
