### ISSUE TITLE
Option to Open PDF in Default App

### ISSUE THREAD

**Issue by mateusfonseca01** [Phantom1003/obsidian-slide-note#9]
Hi Phantom1003, first of all, tks a lot for your plug in, its have been really helpfull for my work flow!

I would like to sugest a option to open de PDF page in the default app. Would help a lot because i often make some of my anottations on the PDF itself and I like to change these annotation quite a bit. The inline notes are helpful but only works inside Obsidian, so to make drawings and highlights I preffer to do these annotations on the PDF.

Thank You a Lot.

**Comment by Phantom1003** [comment]
Sorry, for the late response.
I'm actually considering archiving this plugin, Obsidian supports native PDF deep-linking after upgrading to 1.3.6.
Although Slide Note implements some performance optimizations, I believe users will prefer the official plugin.

**Comment by Phantom1003** [comment]
Hi, 0.0.10 supports opening within your local PDF application now.
You can find the `Slide Note: open with local application` item in the editor menu, Slide Note will try to open the PDF in the the selected code block.
